WeGrus/WeGrus-FE-React

package-lock.json
package.json
src/components/screens/Board.js
src/components/screens/Page.js
src/components/screens/Page_Create.js
src/components/shared/Checkbox.js
src/components/shared/SideBar.js

> PR 종류를 선택해주세요
> #이슈번호 형태로 추가해주세요.
> 변경 사항을 요약해주세요.
- PageCreate.js 기능 구현
- Page.js UI 구현
- SideBar.js, Board.js 리팩토링이 필요한 것 같습니다. 

페이지 라우터 구현

---

package-lock.json
package.json
public/index.html
src/App.js
src/components/auth/FormBox.js
src/components/auth/HeaderContainer.js
src/components/auth/OAuth.js
src/components/auth/UserInfo.js
src/components/screens/EmailAuth.js
src/components/screens/Login.js

- 카카오 oauth의 경우 kapi.kakao.com api 호출은 프론트엔드 스크립트에서 허용되지 않아 백엔드에서 구현하기로 함
- issue 1
- comment 1
- https://kakao-tam.tistory.com/81

Feat: 이메일 인증 api 연동

---

src/components/screens/EmailAuth.js

- issue 1
- comment 1
- reference 1

Etc: 사소한 수정사항

---

src/components/screens/Signup.js
src/store.js
src/variables.js

- issue 1
- comment 1
- reference 1

Feat: 회원가입, 로그인 기능 구현

---

src/components/auth/OAuth.js
src/store.js

- issue 1
- comment 1
- reference 1

Feat: loginSuccess

---

src/App.js
src/components/auth/OAuth.js
src/components/navibar/NavBarElements.js
src/components/navibar/NaviBar.js
src/components/screens/Board.js
src/components/screens/Profile.js
src/components/shared/getUserInfoFn.js
src/store.js

- 유저 데이터 요청 후 store에 저장
- issue 1
- 로그인 api 요청 시 제공되는 회원 번호 정보를 이용해 회원 정보 api를 요청합니다.
- app.js에서 회원 정보를 불러옵니다.
- comment 1
- reference 1

Feat: getUserInfo

---

src/App.js
src/components/Blocker.js
src/components/auth/OAuth.js
src/components/screens/About.js

- issue 1
- comment 1
- reference 1

Feat: About 페이지 진행

---

src/components/auth/OAuth.js
src/components/screens/EmailAuth.js
src/components/screens/Signup.js
src/store.js

- 이메일 인증 여부 확인 로직이 잘 작동 안 되고 있음
- issue 1
- 카카오 로그인 이후로 안 넘어가는 문제를 해결했으나 이메일 인증 여부를 확인하는 로직이 잘 작동이 안 되어 수정이 필요함
- comment 1
- reference 1

Etc: 카카오 로그인 이후로 안 넘어가는 문제 해결

---

src/components/screens/Board.js
src/components/shared/Pagination.js

- issue 1
- 프로필이나 마이페이지 구현하실 때 참고하실 수 있도록 주석을 추가했습니다. 
- 문제점이나 수정할 부분, 궁금하신 점이 있으시면 바로 이슈에 써주시고 카톡 남겨주세요.
- comment 1
- reference 1

Etc: 주석 추가

---

src/App.js
src/components/auth/OAuth.js
src/components/screens/About.js
src/components/screens/EmailAuth.js
src/components/screens/Signup.js
src/store.js

- csrf 방지를 위해 설정한 sameSite lax에서는 다른 도메인간 쿠키 전송이 불가합니다.
- 이를 해결하기 위해서는 (1) 도메인을 통합하거나 (2) https 설정해 secure 설정을 해야 합니다.
- issue 1
- csrf 방지를 위해 설정한 sameSite lax에서는 다른 도메인간 쿠키 전송이 불가합니다.
- 이를 해결하기 위해서는 (1) 도메인을 통합하거나 (2) https 설정해 secure 설정을 해야 합니다.
- 따라서 마지막에 도메인을 통합하여 해당 api를 테스트 하기로 하였습니다.
- comment 1
- 브라우저 쿠키와 SameSite 속성(https://seob.dev/posts/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-%EC%BF%A0%ED%82%A4%EC%99%80-SameSite-%EC%86%8D%EC%84%B1/)
- https://brorica.tistory.com/entry/localhost%EC%97%90%EC%84%9C-httpOnly-cookie-%EC%83%9D%EC%84%B1?category=949090
- https://developer.mozilla.org/ko/docs/Web/HTTP/Cookies

Etc: 리이슈 API 쿠키 안 받아지는 문제

---

src/App.js
src/components/auth/OAuth.js
src/store.js

- 뒤섞인 회원 정보를 알맞게 맞추었습니다.
- issue 1
- userReducer 회원정보 순서 얽히는 문제 해결
- comment 1
- reference 1

Fix: userReducer 회원정보 순서 얽히는 문제 해결

---

src/components/screens/Profile/Profile.js
src/components/screens/Profile/UserInfo.js
src/components/screens/Profile/fileUpload.component.js
src/components/screens/Signup.js

- issue 1
- 프로필 사진 삭제 기능 추가
- 사용자 정보 수정 기능 추가
- comment 1
- reference 1

Feat: 프로필 수정

---

src/App.js
src/components/auth/OAuth.js
src/components/screens/Profile/SavedPosts.js
src/components/screens/Profile/UserComments.js
src/components/screens/Profile/UserInfo.js
src/components/screens/Profile/UserPosts.js
src/components/shared/PostBar.js

- issue 1
- profile의 내가 쓴 게시글 보기 기능을 구현했습니다.
- 현재 백엔드 응답의 totalPages 결괏값이 0 아니면 1로만 나오는 것 같아 수정 요청드린 상태입니다.
- reference 1

Feat: 내가 쓴 게시글

---

src/App.js
src/components/navibar/NaviBar.js
src/components/screens/About.js
src/components/screens/Board.js
src/components/screens/Profile/ProfilePostBar.js
src/components/shared/BoardElement.js
src/components/shared/SideBar.js

- issue 1
- 동아리 가입 버튼을 누르면 가입 신청 api가 호출되고 구글폼 페이지로 이동합니다.
- guest 권한으로 navibar의 다른 곳에 들어가지 못하도록 했습니다.
- comment 1
- reference 1

Feat: 동아리 가입 신청

---

src/components/screens/Page_Create.js

이미지 업로드는 안됩니다.
- 
- 이미지 업로드는 되지 않습니다.
- comment 1
- reference 1

ETC: 임시 작업

---

src/components/navibar/NaviBar.js
src/components/screens/About.js
src/components/screens/Profile/UserAccount.js
src/store.js

- issue 1
- comment 1
- reference 1

Style: about 페이지 style 수정

---

src/components/screens/Page_Create.js

이제 게시물 작성 시 이미지를 base64가 아닌 url로 받습니다.
- issue 1
- 이제 게시물 등록할 때,  이미지가 base64인코딩이 아닌, url로 받을 수 있게 되었습니다. 게시물을 작성할 때, 이미지를 포함하셔도 됩니다.
- 현재 공지글변경이나, 게시글 등록시에 에러가 생기는 것을 발견했습니다. 추후, 수정하도록 하겠습니다.
- reference 1

Feat: 게시물 이미지 서버 등록 적용

---

src/App.js
src/components/screens/About.js
src/components/screens/Board.js
src/components/screens/Profile/GetPosts.js
src/components/screens/Profile/Profile.js
src/components/screens/Profile/ProfilePostBar.js
src/components/screens/Profile/ProfilePostBarElements.js
src/components/screens/Profile/SavedPosts.js
src/components/screens/Profile/UserAccount.js
src/components/screens/Profile/UserComments.js
src/components/screens/Profile/UserGroup.js
src/components/shared/Pagination.js
src/components/shared/PaginationElements.js
src/store.js

- issue 1
- 프로필 게시글 페이지에도 pagination을 적용했습니다.
- 커큐니티 페이지에서 페이지를 2페이지로 놓고 다시 프로필 게시판으로 돌아오면 pageReducer의 page값이 그대로 옯겨져 프로필에도 저장되는 버그가 발생하여 이를 해결하겠습니다.
- reference 1

Feat: 프로필 pagination 구현

---

src/components/screens/Operator.js

groudId 라는 변수가 많아, 계속 버그를 일으켜 변수를 다 제거했습니다.
- issue 1
- 기존의 관리자 페이지에서 발견된 오타와 중복된 변수를 제거해 버그를 제거했습니다.
- comment 1
- reference 1

Fix: 오타수정 및 groudId 중복 제거

---

src/components/screens/Profile/UserGroup.js

- issue 1
- 프로필에 소모임 신청 화면을 구현했습니다.
- comment 1
- reference 1

User group

---

src/components/screens/Operator.js
src/components/screens/Page_Create.js
src/components/shared/BoardEdit.js
src/components/shared/BoardElement.js

- issue 1
- 게시판 추가 및 삭제 기능을 구현했습니다.
- comment 1
- reference 1

Feat: 게시판 삭제, 추가 api 적용

---

package-lock.json
package.json
src/App.js
src/components/navibar/NaviBar.js
src/store.js

- issue 1
- refreshToken이 유효할 경우 reissue api를 호출하여 토큰을 갱신합니다.
- comment 1
- 프론트에서 안전하게 로그인 처리하기(https://velog.io/@yaytomato/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%90%EC%84%9C-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)
배포 후 동작 여부를 확인할 수 있습니다.

Feat: reissue

---

package-lock.json
package.json
src/App.js
src/components/Layout.js
src/components/screens/Announce.js
src/components/screens/Board.js
src/components/screens/Group.js
src/components/screens/Page.js
src/components/screens/PageNew.js
src/components/screens/Page_Create.js
src/components/screens/Study.js
src/components/shared/BoardElement.js
src/components/shared/PageElements.js
src/components/shared/PostBarNew.js

- #69
- #70 
- #72 
- #74
- #75 
- #76 
- #77 
- #78 
- #85 
- #86
- 디자인 수정 및 추가적인 기능을 구현했습니다. 자세한 내용은 이슈를 참고해주세요.
- comment 1
- reference 1

Board correction

---

src/App.js
src/components/auth/OAuth.js

- issue 1
- comment 1
- reference 1

서버 수정 후 app.js 조건문 제거

---

src/components/screens/OtherProfile/OtherProfile.js
src/components/screens/OtherProfile/UserPosts.js

- 
- main 에러 오류로 인한 pr입니다.
- comment 1
- reference 1

Otherprofile

---

package.json
src/App.js
src/components/auth/BottomButton.js
src/components/auth/EmailAuth.js
src/components/auth/OAuth.js
src/components/navibar/NaviBar.js
src/components/screens/Profile/UserPosts.js
src/components/screens/Signup.js
src/components/screens/Study.js
src/components/shared/Comment.js
src/components/shared/Pagination.js
src/components/shared/PaginationNew.js
src/components/shared/PostBarContent.js
src/store.js

- issue 1
- comment 1
- reference 1

사용하지 않은 코드 제거
